# Taps
tap 'mas-cli/tap'
tap 'thoughtbot/formulae'

# Casks
cask '1password'
cask 'appcleaner'
cask 'bitwarden'
cask 'cyberduck'
cask 'docker'
cask 'font-hack'
cask 'iterm2'
cask 'postico'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'the-unarchiver'
cask 'visual-studio-code'

# Packages
brew 'diff-so-fancy'
brew 'doctl'
brew 'duti'
brew 'git'
brew 'git-extras'
brew 'grc'
brew 'jq'
brew 'mas'
brew 'n'
brew 'procs'
brew 'python'
brew 'thoughtbot/formulae/rcm'
brew 'yarn'
brew 'kubectl'

# # Mac App Store
mas "WiFi Explorer Lite", id: 1408727408
