#!/bin/zsh

# Install brew dependencies.
install_brew() {
  echo "Running brew..."
  brew bundle --file=brew/Brewfile
}

# Install zim.
install_zim() {
  ZIM_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/.zim"

  # Download zimfw plugin manager if missing.
  if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
    curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  fi
}

# Setup rc files.
symlink_dotfiles() {
  echo "Symlinking dotfiles..."
  rcup -fvd packages | nl -bn
}

# Install latest node.js.
install_nodejs() {
  if [ ! -x "$(which asdf 2> /dev/null)" ]; then
    return 1;
  fi

  echo "Installing latest node.js..."
  
  asdf plugin add nodejs
  asdf install nodejs lts
  asdf set -u nodejs lts
}

# Configure duti default file handlers.
configure_duti() {
  echo "Applying duti defaults..."

  # VS Code
  local vsCodeExtensions=(json md py sh yaml yml)
  for extension in "${vsCodeExtensions[@]}"
  do
    duti -s com.microsoft.VSCode .${extension} all
  done

  # The Unarchiver
  local unarchiverExtensions=(zip rar)
  for extension in "${unarchiverExtensions[@]}"
  do
    duti -s com.macpaw.site.theunarchiver .${extension} all
  done
}

# Configure iTerm defaults.
configure_iterm() {
  if [ -e ~/Library/Application\ Support/iTerm2/DynamicProfiles ]; then
    echo "Skipping iTerm defaults..."
    return 0;
  fi

  echo "Applying iTerm defaults..."
  mkdir -p ~/Library/Application\ Support/iTerm2/DynamicProfiles
  ln -sfv $(pwd)/library/iterm/profiles/default.json ~/Library/Application\ Support/iTerm2/DynamicProfiles
  source library/iterm/defaults
}

# Configure macOS defaults.
configure_macos() {
  echo "Applying macOS defaults..."
  source macos/defaults
}

install_brew
install_zim
symlink_dotfiles
install_nodejs
configure_duti
configure_iterm
configure_macos
